
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/iorderdb
    username: root
    password: hu8jin7wei@
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: order_service
  config:
    import: configserver:http://localhost:8051


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8050/eureka}